[build]
  publish = "out"
  command = "yarn build"

[build.environment]
  YARN_VERSION = "1.22.17"
  YARN_FLAGS = "--no-ignore-optional"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# ========== HANDBOOK REDIRECTS ==========
[[redirects]]
  from = "/company/*"
  to = "https://handbook.sourcegraph.com/#stq=company"
  status = 301
  force = true

[[redirects]]
  from = "/retrospectives/*"
  to = "https://handbook.sourcegraph.com/company-info-and-process/communication/retrospectives/"
  status = 301
  force = true

[[redirects]]
  from = "/workflow/*"
  to = "https://handbook.sourcegraph.com/#stq=workflow"
  status = 301
  force = true

[[redirects]]
  from = "/search"
  to = "https://handbook.sourcegraph.com/#stq=:q"
  query = {q = ":q"}
  status = 301
  force = true

[[redirects]]
  from = "/handbook/*"
  to = "https://handbook.sourcegraph.com/:splat"
  status = 301
  force = true
# ========== END HANDBOOK REDIRECTS ==========

# ========== INDIVIDUAL REDIRECTS ==========
[[redirects]]
  from = "/terms-private"
  to = "/terms-self-hosted"
  status = 301
  force = true

[[redirects]]
  from = "/contact/sales"
  to = "/contact/product-specialist"
  status = 301
  force = true

[[redirects]]
  from = "/blog/better-onboarding-advice-from-engineering-leaders/"
  to = "/blog/better-onboarding-how-to-prevent-codebase-overwhelm/"
  status = 301
  force = true

[[redirects]]
  from = "/customers"
  to = "/use-cases"
  status = 301
  force = true

[[redirects]]
  from = "/dpa"
  to = "/dpa.pdf"
  status = 301
  force = true

[[redirects]]
  from = "/cloud-beta"
  to = "/"
  status = 301
  force = true
# ========== END INDIVIDUAL REDIRECTS ==========
